CREATE DATABASE IF NOT EXISTS `EMPLOYEE`;
USE `EMPLOYEE`;

CREATE TABLE IF NOT EXISTS `TB_EMPLOYEE`(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DEPARTMENT2 VARCHAR(50) NOT NULL,
    NAME2 VARCHAR(30) NOT NULL,
    MONEY2 INT NOT NULL
);
SELECT * FROM `TB_EMPLOYEE`;
